INSERT INTO nivel1 (descripcion) VALUES ('me gusta confianza');
INSERT INTO nivel1 (descripcion) VALUES ('familia confianza');
INSERT INTO nivel1 (descripcion) VALUES ('kaypacha');

INSERT INTO nivel2 (descripcion, id_nivel1) VALUES ('seguros',1);
INSERT INTO nivel2 (descripcion, id_nivel1) VALUES ('beneficios',1);
INSERT INTO nivel2 (descripcion, id_nivel1) VALUES ('celebraciones',1);
INSERT INTO nivel2 (descripcion, id_nivel1) VALUES ('formación',1);
INSERT INTO nivel2 (descripcion, id_nivel1) VALUES ('en familia',2);
INSERT INTO nivel2 (descripcion, id_nivel1) VALUES ('buenas nuevas',2);
INSERT INTO nivel2 (descripcion, id_nivel1) VALUES ('en confianza',2);
INSERT INTO nivel2 (descripcion, id_nivel1) VALUES ('orgullo fc',2);
INSERT INTO nivel2 (descripcion, id_nivel1) VALUES ('¿qué es?',3);
INSERT INTO nivel2 (descripcion, id_nivel1) VALUES ('agiles',3);
INSERT INTO nivel2 (descripcion, id_nivel1) VALUES ('los  mejores',3);
INSERT INTO nivel2 (descripcion, id_nivel1) VALUES ('hananpacha',3);

INSERT INTO nivel3 (descripcion, id_nivel2) VALUES ('EPS',1);
INSERT INTO nivel3 (descripcion, id_nivel2) VALUES ('Oncológico',1);
INSERT INTO nivel3 (descripcion, id_nivel2) VALUES ('Vida Ley',1);
INSERT INTO nivel3 (descripcion, id_nivel2) VALUES ('Accidentes',1);
INSERT INTO nivel3 (descripcion, id_nivel2) VALUES ('Licencia',2);
INSERT INTO nivel3 (descripcion, id_nivel2) VALUES ('Especiales',2);
INSERT INTO nivel3 (descripcion, id_nivel2) VALUES ('Convenios',2);
INSERT INTO nivel3 (descripcion, id_nivel2) VALUES ('Aniversario',3);
INSERT INTO nivel3 (descripcion, id_nivel2) VALUES ('Fiesta Fin de Año',3);
INSERT INTO nivel3 (descripcion, id_nivel2) VALUES ('Otros',3);
INSERT INTO nivel3 (descripcion, id_nivel2) VALUES ('Capacitaciones',4);
INSERT INTO nivel3 (descripcion, id_nivel2) VALUES ('Felicitaciones',6);
INSERT INTO nivel3 (descripcion, id_nivel2) VALUES ('Bienvenidos',6);
INSERT INTO nivel3 (descripcion, id_nivel2) VALUES ('Historia',8);
INSERT INTO nivel3 (descripcion, id_nivel2) VALUES ('Clientes',8);
INSERT INTO nivel3 (descripcion, id_nivel2) VALUES ('Colaboradores',8);